'use strict';
// Dependency-free synthetic DOM regression checks. No browser, network, or account data.
// This verifies rendering/interaction logic; real browser QA is still needed for layout.
// Run with: node tests/test_web_ui.cjs
const fs = require('fs'), vm = require('vm'), assert = require('assert/strict');
const source = fs.readFileSync(process.argv[2] || require('path').join(__dirname,'..','web','index.html'), 'utf8');
const script = source.match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(script); // Check the full, unmodified product script.
let document;
class Element {
  constructor(tag, text = '') { this.tagName = tag.toUpperCase(); this.childNodes = []; this.parentNode = null; this.attrs = {}; this.dataset = {}; this.style = {}; this.listeners = {}; this._text = text; this.hidden = false; this.open = false; this.value = ''; }
  get value() { return this._value || ''; }
  set value(v) { this._value = String(v); }
  get children() { return this.childNodes.filter(n => n.tagName !== '#TEXT'); }
  get isConnected() { return this === document?.root || !!this.parentNode?.isConnected; }
  get textContent() { return this._text + this.childNodes.map(n => n.textContent).join(''); }
  set textContent(v) { this.replaceChildren(); this._text = String(v); }
  get className() { return this.attrs.class || ''; }
  set className(v) { this.attrs.class = v; }
  get classList() { return {toggle:(name,force) => { const set = new Set(this.className.split(/\s+/).filter(Boolean)), on = force ?? !set.has(name); on ? set.add(name) : set.delete(name); this.className = [...set].join(' '); return on; }}; }
  setAttribute(k,v) { this.attrs[k] = String(v); if (k === 'hidden') this.hidden = true; if (k === 'open') this.open = true; if (k.startsWith('data-')) this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c) => c.toUpperCase())] = String(v); }
  getAttribute(k) { if (k.startsWith('data-')) return this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c) => c.toUpperCase())] ?? null; return this.attrs[k] ?? null; }
  removeAttribute(k) { delete this.attrs[k]; }
  append(...nodes) { for (let n of nodes) { if (typeof n === 'string') n = new Element('#text',n); n.parentNode = this; this.childNodes.push(n); } }
  replaceChildren(...nodes) { for (const n of this.childNodes) n.parentNode = null; this.childNodes = []; this._text = ''; this.append(...nodes); }
  matches(s) { if (s.startsWith('.')) return this.className.split(/\s+/).includes(s.slice(1)); if (s.startsWith('#')) return this.attrs.id === s.slice(1); if (s.startsWith('[')) { const match = s.match(/^\[([^=\]]+)(?:=["']?([^"'\]]*)["']?)?\]$/); return match && (match[2] === undefined ? this.getAttribute(match[1]) !== null : this.getAttribute(match[1]) === match[2]); } return this.tagName.toLowerCase() === s.toLowerCase(); }
  querySelectorAll(s) { return this.children.flatMap(n => [...(n.matches(s) ? [n] : []),...n.querySelectorAll(s)]); }
  querySelector(s) { return this.querySelectorAll(s)[0] || null; }
  addEventListener(name, fn) { (this.listeners[name] ||= []).push(fn); }
  dispatch(name) { for (const fn of this.listeners[name] || []) fn({target:this,preventDefault(){}}); }
  focus() { document.activeElement = this; }
  showModal() { this.open = true; } close() { this.open = false; }
}
document = {root:new Element('root'),activeElement:null,hidden:true,createElement:tag => new Element(tag),createTextNode:text => new Element('#text',text),addEventListener(){}};
document.getElementById = id => document.root.querySelector('#' + id);
document.querySelectorAll = s => document.root.querySelectorAll(s);
document.querySelector = s => document.root.querySelector(s);
const stack = [document.root], voidTags = new Set(['META','LINK','INPUT','BR','HR','IMG']);
for (const token of source.replace(/<style>[\s\S]*?<\/style>/,'').replace(/<script>[\s\S]*?<\/script>/,'').match(/<[^>]+>|[^<]+/g)) {
  if (token.startsWith('<!')) continue;
  if (token.startsWith('</')) { stack.pop(); continue; }
  if (token.startsWith('<')) {
    const tag = token.match(/^<([\w-]+)/)?.[1]; if (!tag) continue;
    const node = new Element(tag);
    for (const a of token.slice(tag.length+1,-1).matchAll(/([\w:-]+)(?:="([^"]*)"|='([^']*)')?/g)) node.setAttribute(a[1],a[2] ?? a[3] ?? '');
    stack.at(-1).append(node); if (!voidTags.has(node.tagName) && !token.endsWith('/>')) stack.push(node);
  } else stack.at(-1).append(document.createTextNode(token));
}
const context = vm.createContext({document,console,URL,Intl,Date,localStorage:{getItem(){return null},setItem(){}},setInterval(){},setTimeout(){},clearTimeout(){},AbortController,fetch(){throw new Error('Synthetic checks must not request the network');}});
vm.runInContext(script,context);
const run = code => vm.runInContext(code,context), el = id => document.getElementById(id);
const tokens = total => ({total,input:total,output:0,cachedInput:0,cacheWriteInput:0,reasoningOutput:0});
const entry = (model,total,amount='0.2') => ({model,label:model === 'gpt-6-astra' ? 'GPT-6 Astra' : model === 'gpt-5.6-luna' ? 'GPT-5.6 Luna' : 'UNSAFE UNKNOWN LABEL',tokens:tokens(total),amount,credits:amount === null ? null : '5',usd:amount,partial:amount === null,unpricedTokens:amount === null ? total : 0,turnCount:1});
const models = [entry('gpt-6-astra',12400000),entry('gpt-5.6-luna',1000000,'0.8'),entry(null,600000,null)];
const turn = {id:'synthetic-turn-a',threadId:'synthetic-thread-a',turnNumber:1,startedAt:1720000000,endedAt:1720000010,status:'complete',quality:'complete',model:null,pricingMetadataStatus:'mixed',tokens:tokens(14000000),models,pricing:{status:'partial',amount:'1',credits:'25',model:null}};
const period = {status:'partial',partial:true,startDate:'2026-01-01',endDate:'2026-02-01',tokens:tokens(14000000),models,amount:'1',credits:'25',turnCount:1,unpricedTokens:600000,unpricedTurnCount:1};
const fixture = {monitoring:{status:'active'},settings:{pricingMode:'official',currencyCode:'USD',currencyName:'美元',currencySymbol:'$',subscriptionRenewalDay:1,currencyPerUsd:'1'},periods:{today:period,subscription:period},conversations:[{id:'synthetic-thread-a',title:'合成任务 A',displayId:'TEST-A',activeTurnCount:0,turnCount:1,sourceType:'main',reading:{complete:true}}],turns:[turn],quota:{buckets:[]}};
let checks = 0;
function check(name, fn) { fn(); checks++; console.log('PASS',name); }
function update(value) { context.fixture = structuredClone(value); run('state = fixture; connected = true; render();'); }
update(fixture);
check('12.4M preserves decimal and exact accessible count',() => { assert.match(el('today-models').textContent,/12\.4M/); assert.match(el('today-models').textContent,/12,400,000 Tokens/); assert.equal(el('today-models').querySelector('.model-tokens').title,'12,400,000 Tokens'); });
check('local shares use full denominator including unknown',() => { const lines = el('today-models').querySelectorAll('.model-share-line'); assert.match(lines[0].textContent,/≈88\.6%/); assert.match(lines[1].textContent,/≈7\.1%/); assert.match(lines[2].textContent,/≈4\.3%/); assert.match(lines[0].getAttribute('aria-label'),/12,400,000 \/ 14,000,000/); });
check('unknown model preserved and unpriced tokens stay visible',() => { const unknown = el('today-models').children[2]; assert.match(unknown.textContent,/未确认模型/); assert.doesNotMatch(unknown.textContent,/UNSAFE/); assert.match(unknown.textContent,/600K/); assert.match(unknown.textContent,/暂无估价/); assert.match(unknown.textContent,/600,000 Tokens 未计价/); });
check('latest and pricing show mixed model label',() => { assert.match(el('latest-meta').textContent,/多模型 · 2 个 · 含未确认用量/); assert.match(el('pricing-context').textContent,/多模型 · 2 个/); assert.equal(el('latest-model-details').hidden,false); assert.equal(el('latest-model-details').querySelectorAll('.model-row').length,3); });
check('history has native accessible disclosure with all model rows',() => { const details = el('history-body').querySelector('details'); assert.ok(details); assert.equal(details.querySelector('summary').getAttribute('aria-label'),'第 1 次提问：查看题内模型明细'); assert.equal(details.querySelectorAll('.model-row').length,3); });
check('disclosure state and keyboard focus survive refresh',() => { const details = el('latest-model-details').querySelector('details'); details.open = true; details.dispatch('toggle'); details.querySelector('summary').focus(); run('render();'); const next = el('latest-model-details').querySelector('details'); assert.notEqual(next,details); assert.equal(next.open,true); assert.equal(document.activeElement,next.querySelector('summary')); });
check('history disclosure state and focus survive refresh',() => { const details = el('history-body').querySelector('details'); details.open = true; details.dispatch('toggle'); details.querySelector('summary').focus(); run('render();'); const next = el('history-body').querySelector('details'); assert.equal(next.open,true); assert.equal(document.activeElement,next.querySelector('summary')); });
check('explicitly separates tokens from official quota/Credits shares',() => { assert.match(el('latest-model-details').textContent,/Token 占比不是官方订阅额度或 Credits 占比/); assert.match(document.root.textContent,/不能据此反推额度/); });
check('tier-only mixed metadata does not imply mixed models',() => { const one = structuredClone(fixture); one.turns[0].models = [entry('gpt-6-astra',14000000)]; one.turns[0].model='gpt-6-astra'; update(one); assert.match(el('latest-meta').textContent,/Astra/); assert.doesNotMatch(el('latest-meta').textContent,/多模型/); });
check('unknown usage is never replaced by legacy default model',() => { const unknown = structuredClone(fixture); unknown.turns[0].model='gpt-6-astra'; unknown.turns[0].models=[entry(null,14000000,null)]; update(unknown); assert.match(el('latest-meta').textContent,/未确认模型/); assert.doesNotMatch(el('latest-meta').textContent,/Astra/); });
check('known plus unknown does not assert a second known model',() => { const mixed = structuredClone(fixture); mixed.turns[0].models=[entry('gpt-6-astra',13400000),entry(null,600000,null)]; update(mixed); assert.match(el('latest-meta').textContent,/Astra · 含未确认用量/); assert.doesNotMatch(el('latest-meta').textContent,/多模型/); });
for (const [code,symbol,name] of [['CNY','¥','人民币'],['USD','$','美元'],['HKD','HK$','港元']]) check('currency render ' + code,() => { const f=structuredClone(fixture); f.settings={...f.settings,currencyCode:code,currencySymbol:symbol,currencyName:name}; update(f); assert.ok(el('today-models').querySelector('.model-details').textContent.includes(symbol+'0.20')); assert.ok(el('latest-model-details').querySelector('.model-details').textContent.includes(symbol+'0.20')); assert.equal(document.querySelectorAll('[data-currency-code]').find(b => b.dataset.currencyCode===code).getAttribute('aria-pressed'),'true'); });
check('legacy API without models remains usable',() => { const old=structuredClone(fixture); delete old.turns[0].models; old.turns[0].model='gpt-6-astra'; delete old.periods.today.models; delete old.periods.subscription.models; update(old); assert.match(el('latest-meta').textContent,/Astra/); assert.equal(el('latest-model-details').hidden,true); assert.equal(el('history-body').querySelector('details'),null); assert.equal(el('today-models-empty').textContent,'模型明细等待服务更新。'); });
check('unknown price keeps period tokens and partial warning',() => { const f=structuredClone(fixture); f.periods.today.status='unavailable'; f.periods.today.amount=null; f.periods.today.credits=null; update(f); assert.equal(el('today-tokens').textContent,'14,000,000'); assert.equal(el('today-amount').textContent,'暂无估价'); assert.match(el('today-note').textContent,/部分统计/); });
check('zero missing and invalid share denominator stays unavailable',() => { assert.equal(run('tokenShare(0,0)'),null); assert.equal(run('tokenShare(2,null)'),null); assert.equal(run('tokenShare(2,1)'),null); assert.equal(run('tokenShare(0,10).label'),'0%'); });
check('tiny shares do not claim zero or 100 percent',() => { assert.equal(run('tokenShare(1,100000).label'),'<0.1%'); assert.equal(run('tokenShare(99999,100000).label'),'>99.9%'); });
check('rounded compact tokens are marked approximate',() => { assert.equal(run('compactTokens(12401234)'),'≈12.4M'); assert.equal(run('compactTokens(12400000)'),'12.4M'); });
check('reading progress and selected conversation stay stable',() => { const f=structuredClone(fixture); f.conversations[0].reading={complete:false,bytesRead:10,fileBytes:100}; f.conversations.push({id:'synthetic-thread-b',title:'合成任务 B',displayId:'TEST-B',activeTurnCount:1,sourceType:'main',reading:{complete:true}}); f.turns.push({...structuredClone(turn),id:'synthetic-turn-b',threadId:'synthetic-thread-b',startedAt:1800000000,status:'running'}); update(f); assert.equal(run('selectedConversationId'),'synthetic-thread-a'); assert.equal(el('reading-notice').hidden,false); assert.match(el('latest-heading').textContent,/已读到/); assert.match(el('running-conversations').textContent,/多模型 · 2 个/); });
check('model label content is inserted as text',() => { const f=structuredClone(fixture); f.periods.today.models[0].label='<img src=x onerror=alert(1)>'; update(f); assert.match(el('today-models').textContent,/<img src=x/); assert.equal(el('today-models').querySelector('img'),null); });
console.log('PASS JavaScript syntax; ' + checks + ' synthetic DOM checks; no network, account data, or real browser used.');
const apiFixture=structuredClone(fixture);
apiFixture.csrfToken='synthetic-only-token';
apiFixture.settings={...apiFixture.settings,pricingMode:'api',usdPerCredit:'0.07',ratePerMillion:'77',exchangeRates:{USD:'1',CNY:'7',HKD:'8'}};
for (const owner of [apiFixture.turns[0],apiFixture.periods.today,apiFixture.periods.subscription]) {
  owner.apiContextUncertainTokens=1000000; owner.apiLongContextTokens=12400000;
  owner.credits=null;
  owner.models[0].apiLongContextTokens=12400000;
  owner.models[1].apiContextUncertainTokens=1000000;
  for (const row of owner.models) {
    row.credits=null;
    if (row.model) row.standardRates={unit:'usd_per_million_tokens',uncachedInput:'2.5',cachedInput:'0.25',output:'15',rateDate:'2026-09-27',sourceUrl:'https://developers.openai.com/api/docs/models/synthetic-model'};
  }
}
apiFixture.turns[0].pricing={status:'partial',amount:'1',usd:'1',credits:null,estimateBasis:'api_slices',apiContextUncertainTokens:1000000,apiLongContextTokens:12400000,sourceUrl:'https://developers.openai.com/api/docs/pricing',rateDate:'2026-09-27'};
update(apiFixture);
check('API labels at period current history and model levels',()=>{for (const id of ['today-money-label','subscription-money-label','pricing-heading','history-pricing-heading','today-models','latest-model-details']) assert.match(el(id).textContent,/API 等价费用（估算）/);});
check('legacy API values never manufacture independent Credit estimates',()=>{assert.equal(el('credit-value').hidden,false); assert.equal(el('today-credits').hidden,false); assert.equal(el('subscription-credits').hidden,false); assert.match(el('credit-value').textContent,/暂不可用/); assert.match(el('today-credits').textContent,/暂不可用/); assert.equal(el('history-body').querySelectorAll('.credit-cell').length,1); assert.match(el('today-models').querySelector('.model-credit-line').textContent,/暂不可用/); assert.doesNotMatch(el('today-models').querySelector('.model-details').textContent,/Credits/);});
check('API model rates come from USD protocol and link source',()=>{const row=el('today-models').children[0]; assert.match(row.textContent,/API Standard 基准单价（USD \/ 百万 Tokens）：普通输入 2.5 · 缓存输入 0.25 · 输出 15/); assert.match(row.textContent,/2026-09-27/); const link=row.querySelector('a'); assert.equal(link.href,'https://developers.openai.com/api/docs/models/synthetic-model'); assert.equal(link.rel,'noopener noreferrer'); assert.equal(link.target,'_blank');});
check('API long and uncertain contexts are separately explained',()=>{assert.match(el('today-models').children[0].textContent,/12,400,000 Tokens 使用长上下文档位/); assert.match(el('today-models').children[0].textContent,/2 倍，输出为 1.5 倍/); assert.match(el('today-models').children[1].textContent,/1,000,000 Tokens 的请求／会话上下文未确认/); assert.match(el('today-pricing-summary').textContent,/1,000,000 Tokens 的请求／会话上下文未确认/); assert.match(el('pricing-note').textContent,/12,400,000 Tokens 使用长上下文档位/); assert.match(el('pricing-note').textContent,/1,000,000 Tokens 的请求／会话上下文未确认/);});
check('API scope keeps cache assumption and excludes fees tax subscription',()=>{assert.match(el('pricing-note').textContent,/已观察到的缓存命中比例/); assert.match(el('cost-disclaimer').textContent,/不含工具附加费、税费/); assert.match(el('cost-disclaimer').textContent,/不是订阅扣款/);});
check('API null-price unknown tokens remain excluded and visible',()=>{const row=el('today-models').children[2]; assert.match(row.textContent,/600K/); assert.match(row.textContent,/暂无估价/); assert.match(row.textContent,/600,000 Tokens 未计价/); assert.match(el('today-money-label').textContent,/可计价部分/);});
check('API hides credit conversion but retains FX and legacy settings',()=>{run('openSettings()'); assert.equal(el('credit-conversion-settings').hidden,true); assert.equal(el('official-settings').hidden,false); assert.equal(el('custom-settings').hidden,true); assert.equal(run('fullSettings().usdPerCredit'),'0.07'); assert.equal(run('fullSettings().ratePerMillion'),'77'); assert.equal(run('fullSettings().pricingMode'),'api'); assert.equal(document.querySelectorAll('[data-settings-currency]').find(b=>b.dataset.settingsCurrency==='CNY').disabled,false);});
for (const [code,symbol,name] of [['CNY','¥','人民币'],['USD','$','美元'],['HKD','HK$','港元']]) check('API currency render and switch enabled '+code,()=>{const f=structuredClone(apiFixture);f.settings={...f.settings,currencyCode:code,currencySymbol:symbol,currencyName:name};update(f);assert.ok(el('cost-value').textContent.startsWith(symbol));assert.ok(el('today-models').querySelector('.model-details').textContent.includes(symbol+'0.20'));const button=document.querySelectorAll('[data-currency-code]').find(b=>b.dataset.currencyCode===code);assert.equal(button.disabled,false);assert.equal(button.getAttribute('aria-pressed'),'true');});
check('API default selected when new settings lack mode',()=>{const f=structuredClone(apiFixture);delete f.settings.pricingMode;update(f);assert.equal(run('pricingMode()'),'api');assert.equal(run('fullSettings().pricingMode'),'api');assert.match(el('pricing-heading').textContent,/API/);});
check('API normal-context rates do not show speculative uncertainty',()=>{const f=structuredClone(apiFixture);f.turns[0].pricing.apiContextUncertainTokens=0;f.turns[0].pricing.apiLongContextTokens=0;f.turns[0].pricing.estimateBasis='api_standard';update(f);assert.doesNotMatch(el('pricing-note').textContent,/中点|2 倍/);});
check('API old protocol without models keeps total and waiting detail',()=>{const f=structuredClone(apiFixture);delete f.turns[0].models;delete f.periods.today.models;update(f);assert.equal(el('cost-value').textContent,'$1.00');assert.equal(el('latest-model-details').hidden,true);assert.equal(el('today-models-empty').textContent,'模型明细等待服务更新。');});
check('legacy official Credit rates remain visible',()=>{const f=structuredClone(fixture);f.periods.today.models[0].standardRates={unit:'credits_per_million_tokens',uncachedInput:'62.5',cachedInput:'6.25',output:'375'};update(f);run('openSettings()');assert.equal(el('credit-conversion-settings').hidden,false);assert.equal(el('credit-value').hidden,false);assert.equal(el('today-credits').hidden,false);assert.match(el('today-models').textContent,/Credits \/ 百万 Tokens/);assert.equal(el('history-body').querySelectorAll('.credit-cell').length,1);});
check('custom mode keeps its own units and disables shortcut FX',()=>{const f=structuredClone(fixture);f.settings={...f.settings,pricingMode:'custom',ratePerMillion:'3',currencyCode:'CUSTOM',currencyName:'点',currencySymbol:''};update(f);run('openSettings()');assert.equal(el('custom-settings').hidden,false);assert.equal(el('official-settings').hidden,true);assert.equal(el('credit-conversion-settings').hidden,true);assert.ok(document.querySelectorAll('[data-currency-code]').every(b=>b.disabled));assert.match(el('cost-value').textContent,/点/);assert.doesNotMatch(el('today-models').querySelector('.model-details').textContent,/API/);});

const quotaNow=Math.floor(Date.now()/1000);
const freshQuota={status:'fresh',updatedAt:quotaNow-20,lastAttemptAt:quotaNow-20,expiresAt:quotaNow+100,staleAfterSeconds:120,refreshing:false,error:null,buckets:[{id:'synthetic-main',label:'合成订阅额度',windows:[{windowMinutes:300,remainingPercent:100,resetsAt:quotaNow+3600}]}]};
function withQuota(quota) { const f=structuredClone(apiFixture); f.quota=structuredClone(quota); update(f); }
check('period cards put monetary total before exact token count',()=>{update(apiFixture);const values=document.querySelectorAll('.period-values');assert.equal(values.length,2);for(const value of values){assert.equal(value.children[0].className,'period-money-block');assert.equal(value.children[1].className,'period-token-block');}assert.equal(el('today-tokens').textContent,'14,000,000');});
check('model categories keep cached input out of ordinary input',()=>{const f=structuredClone(apiFixture);f.periods.today.models[0].tokens={...tokens(105),input:100,cachedInput:70,output:5};update(f);const categories=el('today-models').querySelectorAll('.model-category');assert.equal(categories[0].textContent,'普通输入30');assert.equal(categories[1].textContent,'缓存输入70');assert.equal(categories[2].textContent,'输出5');});
check('model API rateDate contract is shown with source',()=>{update(apiFixture);const row=el('today-models').children[0];assert.match(row.querySelector('.model-rates').textContent,/2026-09-27/);assert.equal(row.querySelector('.model-rates').open,false);});
check('rate disclosure and focus survive polling',()=>{const details=el('today-models').querySelector('.model-rates');details.open=true;details.dispatch('toggle');details.querySelector('summary').focus();run('render()');const next=el('today-models').querySelector('.model-rates');assert.equal(next.open,true);assert.equal(document.activeElement,next.querySelector('summary'));});
check('coverage gaps remain visible next to aggregate costs',()=>{const f=structuredClone(apiFixture);f.monitoring.coverage={registeredTasks:12,readableTasks:5,unreadableTasks:7,backfillingTasks:2};update(f);assert.match(el('coverage-summary').textContent,/7 个任务的记录无法读取/);assert.match(el('coverage-summary').textContent,/2 个正在补读/);assert.match(el('coverage-summary').className,/attention/);assert.match(document.root.textContent,/本任务此题的已记录用量；子任务另列/);});
check('fresh official quota shows current percentage and distinct scope',()=>{withQuota(freshQuota);assert.equal(el('quota-container').hidden,false);assert.match(el('quota-container').textContent,/剩余100%/);assert.equal(el('quota-last-known').hidden,true);assert.match(document.querySelector('.quota-scope').textContent,/不是 API 账户余额/);});
check('16-hour stale quota hides current 100 percent',()=>{withQuota({...freshQuota,status:'stale',updatedAt:quotaNow-16*3600,expiresAt:quotaNow-16*3600+120,error:'合成错误：找不到 Codex CLI'});assert.equal(el('quota-container').hidden,true);assert.equal(el('quota-container').textContent,'');assert.doesNotMatch(el('quota-status').textContent,/100%/);assert.equal(el('quota-last-known').hidden,false);assert.equal(el('quota-last-known').open,false);assert.match(el('quota-last-known-summary').textContent,/查看上次成功记录/);assert.match(el('quota-cached-container').textContent,/当时剩余100%/);assert.match(document.querySelector('.quota-historical-note').textContent,/不能作为当前剩余额度/);assert.match(el('quota-error').textContent,/找不到 Codex CLI/);});
check('refresh error overrides an otherwise fresh quota snapshot',()=>{withQuota({...freshQuota,error:'合成网络错误'});assert.equal(el('quota-container').hidden,true);assert.match(el('quota-status').textContent,/读取失败/);assert.equal(el('quota-error-details').hidden,false);});
check('expired fresh snapshot is hidden even before a new backend state',()=>{withQuota({...freshQuota,updatedAt:quotaNow-500,expiresAt:quotaNow-1});assert.equal(el('quota-container').hidden,true);assert.match(el('quota-status').textContent,/已过期/);});
check('fallback TTL hides old data when expiresAt is absent',()=>{const q={...freshQuota,updatedAt:quotaNow-500};delete q.expiresAt;withQuota(q);assert.equal(el('quota-container').hidden,true);});
check('expired quota reset cannot remain current',()=>{const q=structuredClone(freshQuota);q.buckets[0].windows[0].resetsAt=quotaNow-1;withQuota(q);assert.equal(el('quota-container').hidden,true);});
check('future timestamp is not presented as successful historical data',()=>{withQuota({...freshQuota,updatedAt:quotaNow+600});assert.equal(el('quota-container').hidden,true);assert.equal(el('quota-last-known').hidden,true);});
check('malformed timestamp cannot crash quota rendering',()=>{withQuota({...freshQuota,updatedAt:1e20});assert.equal(el('quota-container').hidden,true);assert.match(el('quota-updated').textContent,/记录时间异常/);});
check('legacy quota API without freshness status stays historical',()=>{const q=structuredClone(freshQuota);delete q.status;withQuota(q);assert.equal(el('quota-container').hidden,true);assert.equal(el('quota-last-known').hidden,false);});
check('unavailable quota does not manufacture zero or 100 percent',()=>{withQuota({status:'unavailable',buckets:[],updatedAt:null,error:null});assert.equal(el('quota-container').textContent,'');assert.equal(el('quota-last-known').hidden,true);assert.doesNotMatch(el('quota-status').textContent,/%/);});
check('refreshing stale quota remains hidden and honestly pending',()=>{withQuota({...freshQuota,status:'stale',refreshing:true});assert.equal(el('quota-container').hidden,true);assert.match(el('quota-status').textContent,/正在读取/);assert.match(el('refresh-quota').textContent,/更新中/);assert.equal(el('refresh-quota').disabled,true);});
check('refreshing fresh quota identifies the displayed value as last success',()=>{withQuota({...freshQuota,refreshing:true});assert.equal(el('quota-container').hidden,false);assert.match(el('quota-status').textContent,/最近成功读取的记录/);});
check('connection loss hides the last fresh quota',()=>{withQuota(freshQuota);run('connected=false;renderQuota()');assert.equal(el('quota-container').hidden,true);assert.match(el('quota-status').textContent,/未连接/);});
check('quota recovers after a successful fresh state',()=>{withQuota({...freshQuota,error:'合成失败'});withQuota(freshQuota);assert.equal(el('quota-container').hidden,false);assert.equal(el('quota-last-known').hidden,true);assert.equal(el('quota-error-details').hidden,true);});
// Official account and conversation fixtures are synthetic and independent of local pricing.
const officialFixture=structuredClone(apiFixture);
officialFixture.quota=structuredClone(freshQuota);
officialFixture.officialCredits={status:'fresh',updatedAt:quotaNow,error:null,balance:'1234.567890',unlimited:false,hasCredits:true,usdEquivalent:'49.38271560',amountEquivalent:'49.38271560',trackingStartAt:quotaNow-600,trackingStartBalance:'1200.000000',netChange:'34.567890',history:[{observedAt:quotaNow-600,balance:'1200.000000'},{observedAt:quotaNow,balance:'1234.567890'}],note:'合成余额记录'};
officialFixture.conversations.push({id:'synthetic-thread-b',title:'合成任务 B',displayId:'TEST-B',activeTurnCount:0,turnCount:0,sourceType:'main',reading:{complete:true}});
officialFixture.officialUsage={'synthetic-thread-a':{status:'fresh',updatedAt:quotaNow,error:null,credits:'12.345678',usd:'0.493827',groups:[{model:'gpt-6-astra',reasoningEffort:'ultra',speed:'ultrafast',credits:'12.345678',tokens:{input:100,cachedInput:70,output:5,total:105}}],note:'合成整段对话记录'}};
function updateOfficial(value=officialFixture) { run("quotaRefreshError=null; quotaRefreshRequested=false; quotaRefreshRetryAt=0; officialUsageRequests.clear(); activeView='overview'; historyAll=false; selectedConversationId='synthetic-thread-a';"); update(value); }
for (const mode of ['api','official','custom']) check('official account remains independent in '+mode,()=>{const f=structuredClone(officialFixture);f.settings.pricingMode=mode;updateOfficial(f);assert.equal(el('official-balance').textContent,'1,234.56789 Credits');assert.equal(el('official-usage-credits').textContent,'12.345678 Credits');assert.equal(el('official-usage-values').hidden,false);assert.equal(document.querySelector('.official-credits-card').hidden,false);assert.match(el('official-credits-badge').textContent,/官方最近记录/);});
check('official decimal precision preserves tiny and large source values',()=>{assert.equal(run("exactOfficialDecimal('0.00000001')"),'0.00000001');assert.equal(run("exactOfficialDecimal('12345678901234567890.000000')"),'12,345,678,901,234,567,890.000000');assert.equal(run("exactOfficialDecimal('1e3')"),null);assert.equal(run('exactOfficialDecimal(1234)'),null);});
check('balance net change and dated history do not claim consumption',()=>{updateOfficial();assert.equal(el('official-net-change').textContent,'+34.56789 Credits');assert.match(el('official-tracking-start').textContent,/1,200 Credits/);assert.match(el('official-balance-history-list').children[0].textContent,/1,234.56789 Credits/);assert.match(document.querySelector('.official-tracking').textContent,/最新 − 起点/);assert.match(document.querySelector('.official-tracking').textContent,/净变化不等于实际消耗/);});
check('negative balance history equivalents and net change are preserved',()=>{const f=structuredClone(officialFixture);Object.assign(f.officialCredits,{balance:'-1.250000',usdEquivalent:'-0.050000',amountEquivalent:'-0.050000',trackingStartBalance:'-0.250000',netChange:'-1.000000',history:[{observedAt:quotaNow,balance:'-1.250000'}]});updateOfficial(f);assert.equal(el('official-balance').textContent,'-1.25 Credits');assert.equal(el('official-equivalent').textContent,'$-0.05');assert.equal(el('official-net-change').textContent,'-1 Credits');assert.match(el('official-tracking-start').textContent,/-0.25/);assert.match(el('official-balance-history-list').textContent,/-1.25/);});
check('official balance uses server USD fallback for custom units',()=>{const f=structuredClone(officialFixture);Object.assign(f.settings,{pricingMode:'custom',currencyCode:'CUSTOM',currencyName:'点',currencySymbol:'?',usdPerCredit:'900'});f.officialCredits.amountEquivalent=null;updateOfficial(f);assert.equal(el('official-equivalent').textContent,'≈US$49.38');assert.match(document.querySelector('.official-credits-card').textContent,/不受本地 Credit 单价设置影响/);});
for (const [currencyCode,currencySymbol,amount] of [['CNY','¥','345.678901'],['HKD','HK$','395.061724']]) check('official equivalent uses provided '+currencyCode+' amount',()=>{const f=structuredClone(officialFixture);Object.assign(f.settings,{currencyCode,currencySymbol});f.officialCredits.amountEquivalent=amount;updateOfficial(f);assert.equal(el('official-equivalent').textContent,'≈'+currencySymbol+({CNY:'345.68',HKD:'395.06'}[currencyCode])+' ≈US$49.38');});
check('credit display trims only insignificant zeros and separates the unit',()=>{const f=structuredClone(officialFixture);f.officialCredits.balance='76543.2109870000';updateOfficial(f);assert.equal(el('official-balance').textContent,'76,543.210987 Credits');assert.equal(el('official-balance').querySelector('.official-credit-number').textContent,'76,543.210987');assert.equal(el('official-balance').querySelector('.official-credit-unit').textContent,' Credits');assert.equal(el('official-balance').title,'76543.2109870000 Credits（来源原精度）');assert.match(el('official-balance').getAttribute('aria-label'),/76543.2109870000/);assert.equal(run("officialCreditText('0.000000010000')"),'0.00000001');assert.equal(run("officialCreditText('123.123456789123456789')"),'123.123456789123456789');});
check('money display rounds to cents with approximate marker and exact accessible source',()=>{const f=structuredClone(officialFixture);f.officialCredits.amountEquivalent='3061.728439480000';updateOfficial(f);assert.equal(el('official-equivalent').textContent,'≈$3,061.73');assert.match(el('official-equivalent').title,/3061.728439480000/);assert.match(el('official-equivalent').getAttribute('aria-label'),/3061.728439480000/);assert.equal(el('official-usage-usd').textContent,'≈US$0.49');assert.match(el('official-usage-usd').title,/0.493827/);});
check('money rounding preserves large integer accuracy and marks only changed values',()=>{assert.equal(run("officialMoneyText('12345678901234567890.995000','$')"),'≈$12,345,678,901,234,567,891.00');assert.equal(run("officialMoneyText('1.230000','$')"),'$1.23');assert.equal(run("officialMoneyText('-0.004','$')"),'≈$0.00');assert.equal(run("officialMoneyText('-1.235','$')"),'≈$-1.24');assert.equal(run("officialMoneyText(null,'$')"),null);});
check('converted currency and USD occupy separate display lines with exact values retained',()=>{const f=structuredClone(officialFixture);Object.assign(f.settings,{currencyCode:'CNY',currencySymbol:'¥'});f.officialCredits.amountEquivalent='345.678901';updateOfficial(f);assert.equal(el('official-equivalent').querySelector('.official-money-primary').textContent,'≈¥345.68');assert.equal(el('official-equivalent').querySelector('.official-money-secondary').textContent,'≈US$49.38');assert.match(el('official-equivalent').title,/¥345.678901/);assert.match(el('official-equivalent').title,/US\$49.38271560/);});
check('missing official values never use local estimated totals',()=>{const f=structuredClone(officialFixture);delete f.officialCredits;delete f.officialUsage;updateOfficial(f);assert.equal(el('official-balance').textContent,'未提供');assert.equal(el('official-equivalent').textContent,'未提供');assert.equal(el('official-net-change').textContent,'未提供');assert.equal(el('official-usage-values').hidden,true);assert.match(el('official-usage-status').textContent,/未提供/);assert.equal(el('refresh-official-usage').disabled,false);});
check('unlimited and no-credit flags do not invent numerical balances',()=>{const f=structuredClone(officialFixture);Object.assign(f.officialCredits,{balance:null,unlimited:true,usdEquivalent:null,amountEquivalent:null});updateOfficial(f);assert.equal(el('official-balance').textContent,'不限额（官方标记）');Object.assign(f.officialCredits,{unlimited:false,hasCredits:false});updateOfficial(f);assert.equal(el('official-balance').textContent,'未提供');assert.match(el('official-balance-flags').textContent,/不推算为零/);f.officialCredits.balance='0.000000';updateOfficial(f);assert.equal(el('official-balance').textContent,'0 Credits');});
check('stale or error balances remain explicitly historical',()=>{for (const change of [{status:'stale'},{error:'合成读取失败'}]){const f=structuredClone(officialFixture);Object.assign(f.officialCredits,change);updateOfficial(f);assert.equal(el('official-credits-badge').textContent,'历史记录');assert.match(el('official-balance-label').textContent,/历史/);assert.equal(el('official-balance').textContent,'1,234.56789 Credits');}});
check('disconnected official account and conversation are historical',()=>{updateOfficial();run('connected=false;renderOfficialCredits();renderOfficialUsage();');assert.match(el('official-credits-badge').textContent,/历史记录 · 已断线/);assert.match(el('official-credits-status').textContent,/此前/);assert.match(el('official-usage-status').textContent,/历史记录/);assert.equal(el('refresh-official-usage').disabled,true);});
check('conversation record scope is entire selected conversation',()=>{updateOfficial();assert.match(el('official-usage-identity').textContent,/合成任务 A · TEST-A/);assert.match(el('official-usage-panel').textContent,/不是本题或今天的用量，也不是钱包实际扣除/);assert.equal(el('official-usage-credits').textContent,'12.345678 Credits');assert.equal(el('official-usage-usd').textContent,'≈US$0.49');});
check('official group separates reasoning from speed and cached subset',()=>{updateOfficial();const group=el('official-usage-groups').children[0];assert.match(group.textContent,/Astra/);assert.match(group.textContent,/思考强度 ultra · 速度 UltraFast/);assert.match(group.textContent,/Tokens 105 · 输入 100（其中缓存 70）· 输出 5/);assert.equal(el('official-usage-details').hidden,false);});
check('conversation switches never reuse another conversation record or auto-request',()=>{updateOfficial();run("chooseConversation('synthetic-thread-b')");assert.match(el('official-usage-identity').textContent,/TEST-B/);assert.equal(el('official-usage-values').hidden,true);assert.match(el('official-usage-status').textContent,/未提供/);assert.equal(run('officialUsageRequests.size'),0);run("chooseConversation('synthetic-thread-a')");assert.equal(el('official-usage-credits').textContent,'12.345678 Credits');});
check('all-conversation history does not imply official aggregation',()=>{updateOfficial();run("historyAll=true;changeTab('history');renderOfficialUsage()");assert.match(el('official-usage-status').textContent,/尚未选定/);assert.equal(el('official-usage-values').hidden,true);assert.equal(el('refresh-official-usage').disabled,true);});
check('official record strings are rendered as text and invalid negative usage rejected',()=>{const f=structuredClone(officialFixture);f.officialUsage['synthetic-thread-a'].groups[0].model='<img src=x>';f.officialUsage['synthetic-thread-a'].credits='-1';updateOfficial(f);assert.match(el('official-usage-groups').textContent,/<img src=x>/);assert.equal(el('official-usage-groups').querySelector('img'),null);assert.equal(el('official-usage-credits').textContent,'未提供');});
check('legacy Credit model rates visibly mark their historical date',()=>{const f=structuredClone(officialFixture);f.settings.pricingMode='official';f.periods.today.models[0].standardRates={unit:'credits_per_million_tokens',uncachedInput:'25',cachedInput:'2.5',output:'150',historical:true,billingBasis:'purchased_credits',rateDate:'2026-09-27',sourceUrl:'https://learn.chatgpt.com/docs/pricing'};updateOfficial(f);const details=el('today-models').querySelector('.model-rates');assert.match(details.textContent,/历史费率快照 · 2026-09-27/);assert.match(details.textContent,/购买 Credits 的本地估算费率/);});
check('Credit speed is a preserved local estimate setting, API remains separate',()=>{const f=structuredClone(officialFixture);f.settings.speedMode='ultrafast';updateOfficial(f);run('openSettings()');assert.equal(run('fullSettings().speedMode'),'ultrafast');assert.equal(el('credit-speed').value,'ultrafast');assert.equal(el('credit-conversion-settings').hidden,true);assert.match(el('credit-speed-hint').textContent,/不修改 Codex 的实际速度/);assert.match(el('credit-speed-hint').textContent,/API 始终按 Standard/);});

// Credit estimates are supplied independently of API monetary results.
const creditsApiFixture=structuredClone(officialFixture);
const creditRates={unit:'credits_per_million_tokens',uncachedInput:'25',cachedInput:'2.5',output:'150',rateDate:'2026-09-30',historical:false,billingBasis:'purchased_credits',sourceUrl:'https://learn.chatgpt.com/docs/pricing'};
const syntheticCredit=(credits,unpricedTokens=0)=>({credits,status:credits===null?'unavailable':unpricedTokens?'partial':'estimated',unpricedTokens,note:'合成 Credit 估算说明',standardRates:null,rateDate:'2026-09-30',historical:false,estimateBasis:'standard'});
for(const owner of [creditsApiFixture.turns[0],creditsApiFixture.periods.today,creditsApiFixture.periods.subscription]) {
  (owner.pricing||owner).creditEstimate=syntheticCredit('11.123457',600000);
  owner.models.forEach((row,i)=>{row.creditEstimate=syntheticCredit(i===0?'9.123456':i===1?'2.000001':null,i===2?600000:0);if(row.model)row.creditEstimate.standardRates=structuredClone(creditRates);});
}
check('default API displays supplied independent Credits at all local summary levels',()=>{updateOfficial(creditsApiFixture);for(const id of ['today-credits','subscription-credits','credit-value']){assert.match(el(id).textContent,/11.123457 Credits（估算）/);assert.match(el(id).textContent,/可计价部分/);assert.equal(el(id).hidden,false);}assert.match(el('history-body').querySelector('.credit-cell').textContent,/11.123457 Credits（估算）/);assert.equal(el('today-amount').textContent,'$1.00');assert.equal(el('cost-value').textContent,'$1.00');assert.match(el('today-credit-note').textContent,/600,000 Tokens 暂不可可靠换算/);});
check('each period current and history model row displays its own Credits',()=>{updateOfficial(creditsApiFixture);for(const id of ['today-models','subscription-models','latest-model-details','history-body']){const rows=el(id).querySelectorAll('.model-credit-line');assert.equal(rows.length,3);assert.match(rows[0].textContent,/9.123456 Credits（估算）/);assert.match(rows[1].textContent,/2.000001 Credits（估算）/);assert.match(rows[2].textContent,/暂不可用 Credits（估算）/);}assert.match(el('today-models').querySelector('.model-credit-line').title,/9.123456 Credits（本地估算原精度）/);});
check('unpriced Credit model keeps Tokens and does not use another rate',()=>{updateOfficial(creditsApiFixture);const row=el('today-models').children[2];assert.match(row.textContent,/600K/);assert.match(row.textContent,/Credits：600,000 Tokens 暂不可可靠换算/);assert.equal(row.querySelector('.credit-rates'),null);assert.doesNotMatch(row.querySelector('.model-credit-line').textContent,/0 Credits/);});
check('API and Credit rate disclosures coexist with distinct units and sources',()=>{updateOfficial(creditsApiFixture);const row=el('today-models').children[0],details=row.querySelectorAll('.model-rates');assert.equal(details.length,2);assert.match(details[0].textContent,/USD \/ 百万 Tokens/);assert.match(details[1].textContent,/Credits \/ 百万 Tokens/);assert.match(details[1].textContent,/当前估算场景：Standard/);assert.equal(details[1].querySelector('a').href,'https://learn.chatgpt.com/docs/pricing');assert.match(details[1].textContent,/2026-09-30/);});
check('Credit rate disclosure state and focus survive polling independently',()=>{updateOfficial(creditsApiFixture);const detail=el('today-models').querySelector('.credit-rates');detail.open=true;detail.dispatch('toggle');detail.querySelector('summary').focus();run('render()');const next=el('today-models').querySelector('.credit-rates');assert.equal(next.open,true);assert.equal(document.activeElement,next.querySelector('summary'));});
check('Credit missing coverage does not inherit API-only unpriced coverage',()=>{const f=structuredClone(creditsApiFixture);f.periods.today.creditEstimate=syntheticCredit('15.000000');f.turns[0].pricing.creditEstimate=syntheticCredit('15.000000');updateOfficial(f);assert.equal(el('today-credits').textContent,'15 Credits（估算）');assert.equal(el('today-credit-note').textContent,'');assert.match(el('today-pricing-summary').textContent,/可计价/);assert.equal(el('credit-coverage').textContent,'');});
check('known API money does not fill unknown Credit conversion',()=>{const f=structuredClone(creditsApiFixture);f.periods.today.models[0].creditEstimate=syntheticCredit(null,12400000);updateOfficial(f);const row=el('today-models').children[0];assert.match(row.querySelector('.model-amount').textContent,/\$0.20/);assert.match(row.querySelector('.model-credit-line').textContent,/暂不可用/);assert.match(row.querySelector('.credit-coverage').textContent,/12,400,000/);});
check('known Credits remain visible when API money is unavailable',()=>{const f=structuredClone(creditsApiFixture);f.periods.today.models[0].amount=null;f.periods.today.amount=null;f.periods.today.status='unavailable';updateOfficial(f);assert.equal(el('today-amount').textContent,'暂无估价');assert.match(el('today-credits').textContent,/11.123457/);const row=el('today-models').children[0];assert.match(row.querySelector('.model-amount').textContent,/暂无估价/);assert.match(row.querySelector('.model-credit-line').textContent,/9.123456/);});
for(const mode of ['api','official','custom']) check('independent Credit estimates are available in '+mode,()=>{const f=structuredClone(creditsApiFixture);f.settings.pricingMode=mode;updateOfficial(f);assert.match(el('today-credits').textContent,/11.123457/);assert.match(el('today-models').querySelector('.model-credit-line').textContent,/9.123456/);assert.equal(el('official-balance').textContent,'1,234.56789 Credits');assert.equal(el('official-usage-credits').textContent,'12.345678 Credits');});
for(const [currencyCode,currencySymbol] of [['USD','$'],['CNY','¥'],['HKD','HK$']]) check('Credit estimate is invariant under '+currencyCode+' display',()=>{const f=structuredClone(creditsApiFixture);Object.assign(f.settings,{currencyCode,currencySymbol});updateOfficial(f);assert.match(el('cost-value').textContent,new RegExp('^'+currencySymbol.replace(/[$]/g,'\\$')));assert.match(el('credit-value').textContent,/11.123457/);assert.match(el('today-models').querySelector('.model-credit-line').textContent,/9.123456/);assert.doesNotMatch(el('credit-value').textContent,/¥|\$|HK/);});
check('local Credits clearly separate saved scenario from API Standard and official records',()=>{const f=structuredClone(creditsApiFixture);f.settings.speedMode='ultrafast';updateOfficial(f);assert.match(el('credit-estimate-scope').textContent,/UltraFast/);assert.match(el('credit-estimate-scope').textContent,/不是官方余额、实际扣除/);assert.match(el('today-models').querySelector('.credit-rates').textContent,/当前估算场景：UltraFast；API 金额仍按 API Standard/);assert.match(el('rate-label').textContent,/API Standard/);});
check('Credit scenario setting stays visible in all monetary modes without changing state',()=>{for(const mode of ['api','official','custom']){const f=structuredClone(creditsApiFixture);f.settings.pricingMode=mode;f.settings.speedMode='standard';updateOfficial(f);run('openSettings()');let item=el('credit-scenario-settings');while(item){assert.equal(item.hidden,false);item=item.parentNode;}assert.equal(el('credit-speed').value,'standard');assert.equal(run('state.settings.speedMode'),'standard');}});
check('historical Credit rate dates remain distinct from API rate dates',()=>{const f=structuredClone(creditsApiFixture);Object.assign(f.periods.today.models[0].creditEstimate.standardRates,{historical:true,rateDate:'2026-09-27'});updateOfficial(f);assert.match(el('today-models').querySelector('.credit-rates').textContent,/历史费率快照 · 2026-09-27/);assert.match(el('today-models').querySelector('.model-rates').textContent,/API Standard/);});
check('explicit unavailable Credit result overrides legacy local credits',()=>{const f=structuredClone(creditsApiFixture);f.settings.pricingMode='official';f.turns[0].pricing.credits='999';f.turns[0].pricing.creditEstimate=syntheticCredit(null,14000000);updateOfficial(f);assert.match(el('credit-value').textContent,/暂不可用/);assert.doesNotMatch(el('credit-value').textContent,/999/);});
check('genuine zero Credit estimate is distinguished from unavailable',()=>{const f=structuredClone(creditsApiFixture);f.periods.today.creditEstimate=syntheticCredit('0.000000');f.periods.today.creditEstimate.status='complete';updateOfficial(f);assert.equal(el('today-credits').textContent,'0 Credits（估算）');assert.equal(el('today-credit-note').textContent,'');});
check('old custom payload never repurposes generic legacy credits',()=>{const f=structuredClone(fixture);f.settings.pricingMode='custom';updateOfficial(f);assert.match(el('credit-value').textContent,/暂不可用/);assert.match(el('today-credits').textContent,/暂不可用/);});

(async()=>{
  update(apiFixture);run('openSettings()');
  el('usd-per-credit').value='not-used-by-api';
  el('rate-per-million').value='not-used-by-api';
  context.posts=[];run('request = async (path,options) => { posts.push({path,body:JSON.parse(options.body)}); return {ok:true}; }; refreshAfterSettings = async () => {};');
  await el('settings-form').listeners.submit[0]({preventDefault(){}});
  check('API save preserves inactive Credit and custom settings',()=>{assert.equal(context.posts.length,1);const posted=context.posts[0].body;assert.equal(posted.pricingMode,'api');assert.equal(posted.usdPerCredit,'0.07');assert.equal(posted.ratePerMillion,'77');assert.equal(posted.exchangeRates.CNY,'7');assert.equal(el('settings-error').hidden,true);});
  for(const code of ['CNY','HKD']) {
    context.posts=[];
    await document.querySelectorAll('[data-currency-code]').find(b=>b.dataset.currencyCode===code).listeners.click[0]({});
    check('API shortcut posts full settings '+code,()=>{assert.equal(context.posts.length,1);const posted=context.posts[0].body;assert.equal(posted.currencyCode,code);assert.equal(posted.pricingMode,'api');assert.equal(posted.usdPerCredit,'0.07');assert.equal(posted.ratePerMillion,'77');});
  }

  withQuota(freshQuota);
  context.refreshReply={ok:true,refresh:{status:'throttled',retryAfterSeconds:30}};
  run('request=async()=>refreshReply; quotaRefreshRetryAt=0;');
  await el('refresh-quota').listeners.click[0]({});
  check('throttled refresh reports cooldown instead of claiming started',()=>{assert.match(el('toast').textContent,/冷却/);assert.doesNotMatch(el('toast').textContent,/已开始/);assert.equal(el('refresh-quota').disabled,true);assert.match(el('refresh-quota').textContent,/秒后可刷新/);});
  run('quotaRefreshRetryAt=0;'); context.refreshReply={ok:true,refresh:{status:'running'}};
  await el('refresh-quota').listeners.click[0]({});
  check('running refresh is reported as already running',()=>assert.equal(el('toast').textContent,'官方额度正在读取中。'));
  context.refreshReply={ok:true,refresh:{status:'started'}};
  await el('refresh-quota').listeners.click[0]({});
  check('started refresh does not claim completed fresh data',()=>assert.equal(el('toast').textContent,'已开始读取官方额度。'));
  run("request=async()=>{throw new Error('合成刷新失败')};");
  await el('refresh-quota').listeners.click[0]({});
  check('failed refresh request hides previously fresh percentage',()=>{assert.equal(el('quota-container').hidden,true);assert.match(el('quota-status').textContent,/读取失败/);assert.equal(el('quota-error').textContent,'合成刷新失败');});
  updateOfficial();
  context.posts=[]; context.refreshReply={ok:true,refresh:{status:'started'}};
  run('request=async(path,options)=>{posts.push({path,body:JSON.parse(options.body),headers:options.headers});return refreshReply};refreshAfterSettings=async()=>{};');
  await el('refresh-official-usage').listeners.click[0]({});
  check('manual official sync posts captured thread and CSRF with 60-second cooldown',()=>{assert.equal(context.posts.length,1);assert.equal(context.posts[0].path,'/api/official-usage-refresh');assert.equal(context.posts[0].body.threadId,'synthetic-thread-a');assert.equal(context.posts[0].headers['X-Meter-Token'],'synthetic-only-token');assert.match(el('official-usage-status').textContent,/已提交/);assert.match(el('refresh-official-usage').textContent,/秒后可同步/);assert.equal(el('refresh-official-usage').disabled,true);});
  await el('refresh-official-usage').listeners.click[0]({});
  check('manual repeated clicks within cooldown do not send another request',()=>assert.equal(context.posts.length,1));
  run("chooseConversation('synthetic-thread-b')");context.refreshReply={ok:true,refresh:{status:'running'}};
  await el('refresh-official-usage').listeners.click[0]({});
  check('other conversation has independent cooldown and running status',()=>{assert.equal(context.posts.length,2);assert.equal(context.posts[1].body.threadId,'synthetic-thread-b');assert.match(el('official-usage-status').textContent,/已有官方记录同步请求/);assert.equal(el('official-usage-values').hidden,true);});
  updateOfficial();context.refreshReply={ok:true,refresh:{status:'throttled',retryAfterSeconds:95}};
  await el('refresh-official-usage').listeners.click[0]({});
  check('official sync throttled response never claims started',()=>{assert.match(el('official-usage-status').textContent,/冷却/);assert.doesNotMatch(el('official-usage-status').textContent,/已提交/);assert.match(el('refresh-official-usage').textContent,/95 秒/);});
  updateOfficial();run("request=async()=>{throw new Error('合成官方同步失败')}");
  await el('refresh-official-usage').listeners.click[0]({});
  check('failed official sync keeps old data marked as history',()=>{assert.equal(el('official-usage-error').textContent,'合成官方同步失败');assert.match(el('official-usage-status').textContent,/历史/);assert.equal(el('official-usage-credits').textContent,'12.345678 Credits');});
  run('state.officialUsage["synthetic-thread-a"].updatedAt=Date.now()/1000;renderOfficialUsage();');
  check('new official record clears an earlier local request failure',()=>{assert.equal(el('official-usage-error').hidden,true);assert.match(el('official-usage-status').textContent,/官方最近记录/);});
  updateOfficial();run('request=()=>new Promise(resolve=>{globalThis.resolveOfficialSync=resolve});');
  const pendingSync=el('refresh-official-usage').listeners.click[0]({});
  run("chooseConversation('synthetic-thread-b')");
  context.resolveOfficialSync({ok:true,refresh:{status:'started'}});await pendingSync;
  check('in-flight sync never changes selected conversation or leaks its state',()=>{assert.equal(run('selectedConversationId'),'synthetic-thread-b');assert.equal(el('official-usage-values').hidden,true);assert.match(el('official-usage-status').textContent,/未提供/);assert.equal(el('refresh-official-usage').disabled,false);});
  const speedFixture=structuredClone(officialFixture);speedFixture.settings.speedMode='ultrafast';updateOfficial(speedFixture);run('openSettings()');el('credit-speed').value='fast';context.posts=[];run('request=async(path,options)=>{posts.push(JSON.parse(options.body));return {ok:true}};');
  await el('settings-form').listeners.submit[0]({preventDefault(){}});
  check('API settings save updates the independent Credit scenario only when chosen',()=>{assert.equal(context.posts[0].speedMode,'fast');assert.equal(context.posts[0].pricingMode,'api');});
  speedFixture.settings.pricingMode='official';updateOfficial(speedFixture);run('openSettings()');el('credit-speed').value='fast';context.posts=[];
  await el('settings-form').listeners.submit[0]({preventDefault(){}});
  check('local Credit settings save selected speed without changing official data',()=>{assert.equal(context.posts[0].speedMode,'fast');assert.equal(context.posts[0].pricingMode,'official');assert.equal(el('official-balance').textContent,'1,234.56789 Credits');});
  console.log('PASS JavaScript syntax; '+checks+' total synthetic DOM checks including API/official/custom; no network or real data.');
})().catch(error=>{console.error(error);process.exitCode=1;});
